services:
  - type: web
    name: battery-monitoring
    env: node
    buildCommand: |
      npm install
      cd frontend
      npm install
      CI=false npm run build
      cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false # This will be configured manually in Render dashboard 