services:
  - type: web
    name: battery-monitoring
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: MONGODB_URI
        sync: false # This will be configured manually in Render dashboard 